version: "3.8"
services:
  testdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bff
      - POSTGRES_PASSWORD=bff
    ports:
      - "5433:5432"
    volumes:
      - testdb:/var/lib/postgresql/data
volumes:
  testdb:
    driver: local
