version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bff
      - POSTGRES_PASSWORD=bff
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - '5775:5775'
      - '6831:6831'
      - '6832:6832'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
volumes:
  db:
    driver: local