apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-api
  annotations:
    iam.gke.io/gcp-service-account: 849144245446-compute@developer.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: bff
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/part-of: bff
    spec:
      serviceAccountName: bff-api
      containers:
        - name: api
          image: ghcr.io/strideynet/bsky-furry-feed/bffsrv:6a5a97ee660cfffbd9584b8337533f3bec35bf0f
          env:
            - name: ENV
              value: production
            - name: BFF_API_ENABLED
              value: "1"
          envFrom:
            - secretRef:
                name: shared-env
          ports:
            - containerPort: 1337
            - containerPort: 1338
              name: debug
          resources:
            requests:
              memory: 512Mi # 512Mi is minimum
              cpu: 250m # 250m is minimum
---
apiVersion: v1
kind: Service
metadata:
  name: bff-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 1337
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: bff
  type: ClusterIP
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: bff-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/part-of: bff
  endpoints:
    - port: debug
      interval: 30s