apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-ingester
  annotations:
    iam.gke.io/gcp-service-account: 849144245446-compute@developer.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-ingester
  labels:
    app.kubernetes.io/name: ingester
    app.kubernetes.io/part-of: bff
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingester
        app.kubernetes.io/part-of: bff
    spec:
      serviceAccountName: bff-ingester
      containers:
      - name: ingester
        image: ghcr.io/strideynet/bsky-furry-feed/bffsrv:fdd5fed1e87d04b726cd32960f0c39b84b2bd833
        env:
          - name: ENV
            value: production
        envFrom:
          - secretRef:
              name: shared-env
        ports:
        - containerPort: 1337
        - containerPort: 1338
          name: debug
        resources:
          requests:
            memory: 512Mi # 512Mi is minimum
            cpu: 500m # 250m is minimum
---
apiVersion: v1
kind: Service
metadata:
  name: bff-ingester
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 1337
  selector:
    app.kubernetes.io/name: ingester
    app.kubernetes.io/part-of: bff
  type: ClusterIP
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: bff-ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: bff
  endpoints:
    - port: debug
      interval: 30s