apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-ingester
  annotations:
    iam.gke.io/gcp-service-account: 849144245446-compute@developer.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-ingester
  labels:
    app.kubernetes.io/name: ingester
    app.kubernetes.io/part-of: bff
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingester
        app.kubernetes.io/part-of: bff
    spec:
      serviceAccountName: bff-ingester
      containers:
      - name: ingester
        image: ghcr.io/strideynet/bsky-furry-feed/bffsrv:v0.0.20
        env:
          - name: ENV
            value: production
          - name: BFF_INGESTER_ENABLED
            value: "1"
        envFrom:
          - secretRef:
              name: shared-env
        ports:
        - containerPort: 1337
        - containerPort: 1338
          name: debug
        resources:
          requests:
            memory: 512Mi # 512Mi is minimum
            cpu: 250m # 250m is minimum in 250m increments
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: bff-ingester
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingester
      app.kubernetes.io/part-of: bff
  endpoints:
    - port: debug
      interval: 30s