// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bff/v1/moderation_service.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalQueueAction int32

const (
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED ApprovalQueueAction = 0
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_APPROVE     ApprovalQueueAction = 1
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_REJECT      ApprovalQueueAction = 2
)

// Enum value maps for ApprovalQueueAction.
var (
	ApprovalQueueAction_name = map[int32]string{
		0: "APPROVAL_QUEUE_ACTION_UNSPECIFIED",
		1: "APPROVAL_QUEUE_ACTION_APPROVE",
		2: "APPROVAL_QUEUE_ACTION_REJECT",
	}
	ApprovalQueueAction_value = map[string]int32{
		"APPROVAL_QUEUE_ACTION_UNSPECIFIED": 0,
		"APPROVAL_QUEUE_ACTION_APPROVE":     1,
		"APPROVAL_QUEUE_ACTION_REJECT":      2,
	}
)

func (x ApprovalQueueAction) Enum() *ApprovalQueueAction {
	p := new(ApprovalQueueAction)
	*p = x
	return p
}

func (x ApprovalQueueAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalQueueAction) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_v1_moderation_service_proto_enumTypes[0].Descriptor()
}

func (ApprovalQueueAction) Type() protoreflect.EnumType {
	return &file_bff_v1_moderation_service_proto_enumTypes[0]
}

func (x ApprovalQueueAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalQueueAction.Descriptor instead.
func (ApprovalQueueAction) EnumDescriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

type AuditEventType int32

const (
	AuditEventType_COMMENT        AuditEventType = 0
	AuditEventType_APPROVED       AuditEventType = 1
	AuditEventType_REJECTED       AuditEventType = 2
	AuditEventType_HELD_BACK      AuditEventType = 3
	AuditEventType_FORCE_APPROVED AuditEventType = 4
	AuditEventType_UNAPPROVED     AuditEventType = 5
	AuditEventType_TRACKED        AuditEventType = 6
	AuditEventType_BANNED         AuditEventType = 7
	AuditEventType_ASSIGNED_ROLES AuditEventType = 8
)

// Enum value maps for AuditEventType.
var (
	AuditEventType_name = map[int32]string{
		0: "COMMENT",
		1: "APPROVED",
		2: "REJECTED",
		3: "HELD_BACK",
		4: "FORCE_APPROVED",
		5: "UNAPPROVED",
		6: "TRACKED",
		7: "BANNED",
		8: "ASSIGNED_ROLES",
	}
	AuditEventType_value = map[string]int32{
		"COMMENT":        0,
		"APPROVED":       1,
		"REJECTED":       2,
		"HELD_BACK":      3,
		"FORCE_APPROVED": 4,
		"UNAPPROVED":     5,
		"TRACKED":        6,
		"BANNED":         7,
		"ASSIGNED_ROLES": 8,
	}
)

func (x AuditEventType) Enum() *AuditEventType {
	p := new(AuditEventType)
	*p = x
	return p
}

func (x AuditEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_v1_moderation_service_proto_enumTypes[1].Descriptor()
}

func (AuditEventType) Type() protoreflect.EnumType {
	return &file_bff_v1_moderation_service_proto_enumTypes[1]
}

func (x AuditEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEventType.Descriptor instead.
func (AuditEventType) EnumDescriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type GetActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorResponse) Reset() {
	*x = GetActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorResponse) ProtoMessage() {}

func (x *GetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorResponse.ProtoReflect.Descriptor instead.
func (*GetActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListActorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterStatus  ActorStatus            `protobuf:"varint,3,opt,name=filter_status,json=filterStatus,proto3,enum=bff.v1.ActorStatus" json:"filter_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListActorsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListActorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActorsRequest) GetFilterStatus() ActorStatus {
	if x != nil {
		return x.FilterStatus
	}
	return ActorStatus_ACTOR_STATUS_UNSPECIFIED
}

type ListActorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actors        []*Actor               `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *ListActorsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{5}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{6}
}

type ProcessApprovalQueueRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Did      string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Action   ApprovalQueueAction    `protobuf:"varint,2,opt,name=action,proto3,enum=bff.v1.ApprovalQueueAction" json:"action,omitempty"`
	IsArtist bool                   `protobuf:"varint,3,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	// reason is the reason that the actor was approved or rejected. This is
	// currently optional but will become required for rejections eventually.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessApprovalQueueRequest) Reset() {
	*x = ProcessApprovalQueueRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueRequest) ProtoMessage() {}

func (x *ProcessApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessApprovalQueueRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ProcessApprovalQueueRequest) GetAction() ApprovalQueueAction {
	if x != nil {
		return x.Action
	}
	return ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED
}

func (x *ProcessApprovalQueueRequest) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *ProcessApprovalQueueRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProcessApprovalQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessApprovalQueueResponse) Reset() {
	*x = ProcessApprovalQueueResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessApprovalQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueResponse) ProtoMessage() {}

func (x *ProcessApprovalQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueResponse.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{8}
}

// ProcessApprovalQueueAuditPayload is the payload for the
// `process_approval_queue` audit event.
type ProcessApprovalQueueAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ApprovalQueueAction    `protobuf:"varint,1,opt,name=action,proto3,enum=bff.v1.ApprovalQueueAction" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessApprovalQueueAuditPayload) Reset() {
	*x = ProcessApprovalQueueAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessApprovalQueueAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueAuditPayload) ProtoMessage() {}

func (x *ProcessApprovalQueueAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueAuditPayload.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessApprovalQueueAuditPayload) GetAction() ApprovalQueueAction {
	if x != nil {
		return x.Action
	}
	return ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED
}

func (x *ProcessApprovalQueueAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HoldBackPendingActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldBackPendingActorRequest) Reset() {
	*x = HoldBackPendingActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldBackPendingActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorRequest) ProtoMessage() {}

func (x *HoldBackPendingActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorRequest.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{10}
}

func (x *HoldBackPendingActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *HoldBackPendingActorRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type HoldBackPendingActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldBackPendingActorResponse) Reset() {
	*x = HoldBackPendingActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldBackPendingActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorResponse) ProtoMessage() {}

func (x *HoldBackPendingActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorResponse.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{11}
}

type HoldBackPendingActorAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeldUntil     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldBackPendingActorAuditPayload) Reset() {
	*x = HoldBackPendingActorAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldBackPendingActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorAuditPayload) ProtoMessage() {}

func (x *HoldBackPendingActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorAuditPayload.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{12}
}

func (x *HoldBackPendingActorAuditPayload) GetHeldUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

type ListAuditEventsRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FilterActorDid         string                 `protobuf:"bytes,1,opt,name=filter_actor_did,json=filterActorDid,proto3" json:"filter_actor_did,omitempty"`
	FilterSubjectDid       string                 `protobuf:"bytes,2,opt,name=filter_subject_did,json=filterSubjectDid,proto3" json:"filter_subject_did,omitempty"`
	FilterSubjectRecordUri string                 `protobuf:"bytes,3,opt,name=filter_subject_record_uri,json=filterSubjectRecordUri,proto3" json:"filter_subject_record_uri,omitempty"`
	FilterTypes            []AuditEventType       `protobuf:"varint,6,rep,packed,name=filter_types,json=filterTypes,proto3,enum=bff.v1.AuditEventType" json:"filter_types,omitempty"`
	// limit specifies how many audit events to return. If unspecific, this
	// defaults to 100.
	Limit         uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsRequest) Reset() {
	*x = ListAuditEventsRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsRequest) ProtoMessage() {}

func (x *ListAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListAuditEventsRequest) GetFilterActorDid() string {
	if x != nil {
		return x.FilterActorDid
	}
	return ""
}

func (x *ListAuditEventsRequest) GetFilterSubjectDid() string {
	if x != nil {
		return x.FilterSubjectDid
	}
	return ""
}

func (x *ListAuditEventsRequest) GetFilterSubjectRecordUri() string {
	if x != nil {
		return x.FilterSubjectRecordUri
	}
	return ""
}

func (x *ListAuditEventsRequest) GetFilterTypes() []AuditEventType {
	if x != nil {
		return x.FilterTypes
	}
	return nil
}

func (x *ListAuditEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListAuditEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditEvents   []*AuditEvent          `protobuf:"bytes,1,rep,name=audit_events,json=auditEvents,proto3" json:"audit_events,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsResponse) Reset() {
	*x = ListAuditEventsResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsResponse) ProtoMessage() {}

func (x *ListAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListAuditEventsResponse) GetAuditEvents() []*AuditEvent {
	if x != nil {
		return x.AuditEvents
	}
	return nil
}

func (x *ListAuditEventsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type CreateCommentAuditEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubjectDid       string                 `protobuf:"bytes,1,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	SubjectRecordUri string                 `protobuf:"bytes,2,opt,name=subject_record_uri,json=subjectRecordUri,proto3" json:"subject_record_uri,omitempty"`
	Comment          string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCommentAuditEventRequest) Reset() {
	*x = CreateCommentAuditEventRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentAuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAuditEventRequest) ProtoMessage() {}

func (x *CreateCommentAuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAuditEventRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentAuditEventRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentAuditEventRequest) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *CreateCommentAuditEventRequest) GetSubjectRecordUri() string {
	if x != nil {
		return x.SubjectRecordUri
	}
	return ""
}

func (x *CreateCommentAuditEventRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateCommentAuditEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditEvent    *AuditEvent            `protobuf:"bytes,1,opt,name=audit_event,json=auditEvent,proto3" json:"audit_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentAuditEventResponse) Reset() {
	*x = CreateCommentAuditEventResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentAuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAuditEventResponse) ProtoMessage() {}

func (x *CreateCommentAuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAuditEventResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentAuditEventResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentAuditEventResponse) GetAuditEvent() *AuditEvent {
	if x != nil {
		return x.AuditEvent
	}
	return nil
}

// CommentAuditPayload is the payload for the `comment`audit event. This is
// empty, as the comment is actually held within `AuditEvent`
type CommentAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentAuditPayload) Reset() {
	*x = CommentAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentAuditPayload) ProtoMessage() {}

func (x *CommentAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentAuditPayload.ProtoReflect.Descriptor instead.
func (*CommentAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{17}
}

func (x *CommentAuditPayload) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorDid      string                 `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorRequest) Reset() {
	*x = CreateActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorRequest) ProtoMessage() {}

func (x *CreateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorRequest.ProtoReflect.Descriptor instead.
func (*CreateActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{18}
}

func (x *CreateActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *CreateActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorResponse) Reset() {
	*x = CreateActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorResponse) ProtoMessage() {}

func (x *CreateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorResponse.ProtoReflect.Descriptor instead.
func (*CreateActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{19}
}

func (x *CreateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type CreateActorAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActorAuditPayload) Reset() {
	*x = CreateActorAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorAuditPayload) ProtoMessage() {}

func (x *CreateActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorAuditPayload.ProtoReflect.Descriptor instead.
func (*CreateActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnapproveActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorDid      string                 `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnapproveActorRequest) Reset() {
	*x = UnapproveActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnapproveActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorRequest) ProtoMessage() {}

func (x *UnapproveActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorRequest.ProtoReflect.Descriptor instead.
func (*UnapproveActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{21}
}

func (x *UnapproveActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *UnapproveActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnapproveActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnapproveActorResponse) Reset() {
	*x = UnapproveActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnapproveActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorResponse) ProtoMessage() {}

func (x *UnapproveActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorResponse.ProtoReflect.Descriptor instead.
func (*UnapproveActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{22}
}

func (x *UnapproveActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type UnapproveActorAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnapproveActorAuditPayload) Reset() {
	*x = UnapproveActorAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnapproveActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorAuditPayload) ProtoMessage() {}

func (x *UnapproveActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorAuditPayload.ProtoReflect.Descriptor instead.
func (*UnapproveActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{23}
}

func (x *UnapproveActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForceApproveActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorDid      string                 `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceApproveActorRequest) Reset() {
	*x = ForceApproveActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceApproveActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorRequest) ProtoMessage() {}

func (x *ForceApproveActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorRequest.ProtoReflect.Descriptor instead.
func (*ForceApproveActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{24}
}

func (x *ForceApproveActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *ForceApproveActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForceApproveActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceApproveActorResponse) Reset() {
	*x = ForceApproveActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceApproveActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorResponse) ProtoMessage() {}

func (x *ForceApproveActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorResponse.ProtoReflect.Descriptor instead.
func (*ForceApproveActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{25}
}

func (x *ForceApproveActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ForceApproveActorAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceApproveActorAuditPayload) Reset() {
	*x = ForceApproveActorAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceApproveActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorAuditPayload) ProtoMessage() {}

func (x *ForceApproveActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorAuditPayload.ProtoReflect.Descriptor instead.
func (*ForceApproveActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{26}
}

func (x *ForceApproveActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorDid      string                 `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanActorRequest) Reset() {
	*x = BanActorRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorRequest) ProtoMessage() {}

func (x *BanActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorRequest.ProtoReflect.Descriptor instead.
func (*BanActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{27}
}

func (x *BanActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *BanActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanActorResponse) Reset() {
	*x = BanActorResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorResponse) ProtoMessage() {}

func (x *BanActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorResponse.ProtoReflect.Descriptor instead.
func (*BanActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{28}
}

func (x *BanActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type BanActorAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanActorAuditPayload) Reset() {
	*x = BanActorAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorAuditPayload) ProtoMessage() {}

func (x *BanActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorAuditPayload.ProtoReflect.Descriptor instead.
func (*BanActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{29}
}

func (x *BanActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuditEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier of this audit event.
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// actor_did is the DID of the actor whose action caused this audit event
	// to be emitted.
	ActorDid string `protobuf:"bytes,3,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	// subject_did is the DID of the actor who the action was done to.
	SubjectDid string `protobuf:"bytes,4,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	// subject_record_uri is the optional AT URI of a specific ATProto record
	// that the action was taken against.
	SubjectRecordUri string     `protobuf:"bytes,5,opt,name=subject_record_uri,json=subjectRecordUri,proto3" json:"subject_record_uri,omitempty"`
	Payload          *anypb.Any `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{30}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditEvent) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *AuditEvent) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *AuditEvent) GetSubjectRecordUri() string {
	if x != nil {
		return x.SubjectRecordUri
	}
	return ""
}

func (x *AuditEvent) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{31}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         map[string]*Role       `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{32}
}

func (x *ListRolesResponse) GetRoles() map[string]*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{33}
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AssignRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorDid      string                 `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesRequest) Reset() {
	*x = AssignRolesRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesRequest) ProtoMessage() {}

func (x *AssignRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{34}
}

func (x *AssignRolesRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *AssignRolesRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesResponse) Reset() {
	*x = AssignRolesResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesResponse) ProtoMessage() {}

func (x *AssignRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesResponse.ProtoReflect.Descriptor instead.
func (*AssignRolesResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{35}
}

type AssignRolesAuditPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolesBefore   []string               `protobuf:"bytes,1,rep,name=roles_before,json=rolesBefore,proto3" json:"roles_before,omitempty"`
	RolesAfter    []string               `protobuf:"bytes,2,rep,name=roles_after,json=rolesAfter,proto3" json:"roles_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesAuditPayload) Reset() {
	*x = AssignRolesAuditPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesAuditPayload) ProtoMessage() {}

func (x *AssignRolesAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesAuditPayload.ProtoReflect.Descriptor instead.
func (*AssignRolesAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{36}
}

func (x *AssignRolesAuditPayload) GetRolesBefore() []string {
	if x != nil {
		return x.RolesBefore
	}
	return nil
}

func (x *AssignRolesAuditPayload) GetRolesAfter() []string {
	if x != nil {
		return x.RolesAfter
	}
	return nil
}

type AttachmentAuditEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentIds []int64                `protobuf:"varint,1,rep,packed,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentAuditEventPayload) Reset() {
	*x = AttachmentAuditEventPayload{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentAuditEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentAuditEventPayload) ProtoMessage() {}

func (x *AttachmentAuditEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentAuditEventPayload.ProtoReflect.Descriptor instead.
func (*AttachmentAuditEventPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{37}
}

func (x *AttachmentAuditEventPayload) GetAttachmentIds() []int64 {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

type CreateAttachmentAuditEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectDid    string                 `protobuf:"bytes,1,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentAuditEventRequest) Reset() {
	*x = CreateAttachmentAuditEventRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentAuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentAuditEventRequest) ProtoMessage() {}

func (x *CreateAttachmentAuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentAuditEventRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentAuditEventRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{38}
}

func (x *CreateAttachmentAuditEventRequest) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *CreateAttachmentAuditEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAttachmentAuditEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentAuditEventResponse) Reset() {
	*x = CreateAttachmentAuditEventResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentAuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentAuditEventResponse) ProtoMessage() {}

func (x *CreateAttachmentAuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentAuditEventResponse.ProtoReflect.Descriptor instead.
func (*CreateAttachmentAuditEventResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{39}
}

type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  int64                  `protobuf:"varint,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{40}
}

func (x *GetAttachmentRequest) GetAttachmentId() int64 {
	if x != nil {
		return x.AttachmentId
	}
	return 0
}

type GetAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MimeType      string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentResponse) Reset() {
	*x = GetAttachmentResponse{}
	mi := &file_bff_v1_moderation_service_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentResponse) ProtoMessage() {}

func (x *GetAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{41}
}

func (x *GetAttachmentResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetAttachmentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_bff_v1_moderation_service_proto protoreflect.FileDescriptor

const file_bff_v1_moderation_service_proto_rawDesc = "" +
	"\n" +
	"\x1fbff/v1/moderation_service.proto\x12\x06bff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/protobuf/any.proto\x1a\x12bff/v1/types.proto\"\x8e\x01\n" +
	"\x04Post\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"indexed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\"#\n" +
	"\x0fGetActorRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\"7\n" +
	"\x10GetActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05actor\"{\n" +
	"\x11ListActorsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x128\n" +
	"\rfilter_status\x18\x03 \x01(\x0e2\x13.bff.v1.ActorStatusR\ffilterStatus\"S\n" +
	"\x12ListActorsResponse\x12%\n" +
	"\x06actors\x18\x01 \x03(\v2\r.bff.v1.ActorR\x06actors\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x99\x01\n" +
	"\x1bProcessApprovalQueueRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x123\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1b.bff.v1.ApprovalQueueActionR\x06action\x12\x1b\n" +
	"\tis_artist\x18\x03 \x01(\bR\bisArtist\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x1e\n" +
	"\x1cProcessApprovalQueueResponse\"o\n" +
	" ProcessApprovalQueueAuditPayload\x123\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1b.bff.v1.ApprovalQueueActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"f\n" +
	"\x1bHoldBackPendingActorRequest\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\x1e\n" +
	"\x1cHoldBackPendingActorResponse\"]\n" +
	" HoldBackPendingActorAuditPayload\x129\n" +
	"\n" +
	"held_until\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\"\x94\x02\n" +
	"\x16ListAuditEventsRequest\x12(\n" +
	"\x10filter_actor_did\x18\x01 \x01(\tR\x0efilterActorDid\x12,\n" +
	"\x12filter_subject_did\x18\x02 \x01(\tR\x10filterSubjectDid\x129\n" +
	"\x19filter_subject_record_uri\x18\x03 \x01(\tR\x16filterSubjectRecordUri\x129\n" +
	"\ffilter_types\x18\x06 \x03(\x0e2\x16.bff.v1.AuditEventTypeR\vfilterTypes\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"h\n" +
	"\x17ListAuditEventsResponse\x125\n" +
	"\faudit_events\x18\x01 \x03(\v2\x12.bff.v1.AuditEventR\vauditEvents\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x89\x01\n" +
	"\x1eCreateCommentAuditEventRequest\x12\x1f\n" +
	"\vsubject_did\x18\x01 \x01(\tR\n" +
	"subjectDid\x12,\n" +
	"\x12subject_record_uri\x18\x02 \x01(\tR\x10subjectRecordUri\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"V\n" +
	"\x1fCreateCommentAuditEventResponse\x123\n" +
	"\vaudit_event\x18\x01 \x01(\v2\x12.bff.v1.AuditEventR\n" +
	"auditEvent\"/\n" +
	"\x13CommentAuditPayload\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\"I\n" +
	"\x12CreateActorRequest\x12\x1b\n" +
	"\tactor_did\x18\x01 \x01(\tR\bactorDid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\":\n" +
	"\x13CreateActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05actor\"1\n" +
	"\x17CreateActorAuditPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"L\n" +
	"\x15UnapproveActorRequest\x12\x1b\n" +
	"\tactor_did\x18\x01 \x01(\tR\bactorDid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\x16UnapproveActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05actor\"4\n" +
	"\x1aUnapproveActorAuditPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"O\n" +
	"\x18ForceApproveActorRequest\x12\x1b\n" +
	"\tactor_did\x18\x01 \x01(\tR\bactorDid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x19ForceApproveActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05actor\"7\n" +
	"\x1dForceApproveActorAuditPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"F\n" +
	"\x0fBanActorRequest\x12\x1b\n" +
	"\tactor_did\x18\x01 \x01(\tR\bactorDid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x10BanActorResponse\x12#\n" +
	"\x05actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05actor\".\n" +
	"\x14BanActorAuditPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xf3\x01\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tactor_did\x18\x03 \x01(\tR\bactorDid\x12\x1f\n" +
	"\vsubject_did\x18\x04 \x01(\tR\n" +
	"subjectDid\x12,\n" +
	"\x12subject_record_uri\x18\x05 \x01(\tR\x10subjectRecordUri\x12.\n" +
	"\apayload\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x12\n" +
	"\x10ListRolesRequest\"\x97\x01\n" +
	"\x11ListRolesResponse\x12:\n" +
	"\x05roles\x18\x01 \x03(\v2$.bff.v1.ListRolesResponse.RolesEntryR\x05roles\x1aF\n" +
	"\n" +
	"RolesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.bff.v1.RoleR\x05value:\x028\x01\"(\n" +
	"\x04Role\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\"G\n" +
	"\x12AssignRolesRequest\x12\x1b\n" +
	"\tactor_did\x18\x01 \x01(\tR\bactorDid\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\x15\n" +
	"\x13AssignRolesResponse\"]\n" +
	"\x17AssignRolesAuditPayload\x12!\n" +
	"\froles_before\x18\x01 \x03(\tR\vrolesBefore\x12\x1f\n" +
	"\vroles_after\x18\x02 \x03(\tR\n" +
	"rolesAfter\"D\n" +
	"\x1bAttachmentAuditEventPayload\x12%\n" +
	"\x0eattachment_ids\x18\x01 \x03(\x03R\rattachmentIds\"X\n" +
	"!CreateAttachmentAuditEventRequest\x12\x1f\n" +
	"\vsubject_did\x18\x01 \x01(\tR\n" +
	"subjectDid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"$\n" +
	"\"CreateAttachmentAuditEventResponse\";\n" +
	"\x14GetAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\x03R\fattachmentId\"H\n" +
	"\x15GetAttachmentResponse\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*\x81\x01\n" +
	"\x13ApprovalQueueAction\x12%\n" +
	"!APPROVAL_QUEUE_ACTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAPPROVAL_QUEUE_ACTION_APPROVE\x10\x01\x12 \n" +
	"\x1cAPPROVAL_QUEUE_ACTION_REJECT\x10\x02*\x99\x01\n" +
	"\x0eAuditEventType\x12\v\n" +
	"\aCOMMENT\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\r\n" +
	"\tHELD_BACK\x10\x03\x12\x12\n" +
	"\x0eFORCE_APPROVED\x10\x04\x12\x0e\n" +
	"\n" +
	"UNAPPROVED\x10\x05\x12\v\n" +
	"\aTRACKED\x10\x06\x12\n" +
	"\n" +
	"\x06BANNED\x10\a\x12\x12\n" +
	"\x0eASSIGNED_ROLES\x10\b2\xed\t\n" +
	"\x11ModerationService\x123\n" +
	"\x04Ping\x12\x13.bff.v1.PingRequest\x1a\x14.bff.v1.PingResponse\"\x00\x12c\n" +
	"\x14ProcessApprovalQueue\x12#.bff.v1.ProcessApprovalQueueRequest\x1a$.bff.v1.ProcessApprovalQueueResponse\"\x00\x12c\n" +
	"\x14HoldBackPendingActor\x12#.bff.v1.HoldBackPendingActorRequest\x1a$.bff.v1.HoldBackPendingActorResponse\"\x00\x12E\n" +
	"\n" +
	"ListActors\x12\x19.bff.v1.ListActorsRequest\x1a\x1a.bff.v1.ListActorsResponse\"\x00\x12?\n" +
	"\bGetActor\x12\x17.bff.v1.GetActorRequest\x1a\x18.bff.v1.GetActorResponse\"\x00\x12?\n" +
	"\bBanActor\x12\x17.bff.v1.BanActorRequest\x1a\x18.bff.v1.BanActorResponse\"\x00\x12Q\n" +
	"\x0eUnapproveActor\x12\x1d.bff.v1.UnapproveActorRequest\x1a\x1e.bff.v1.UnapproveActorResponse\"\x00\x12Z\n" +
	"\x11ForceApproveActor\x12 .bff.v1.ForceApproveActorRequest\x1a!.bff.v1.ForceApproveActorResponse\"\x00\x12H\n" +
	"\vCreateActor\x12\x1a.bff.v1.CreateActorRequest\x1a\x1b.bff.v1.CreateActorResponse\"\x00\x12T\n" +
	"\x0fListAuditEvents\x12\x1e.bff.v1.ListAuditEventsRequest\x1a\x1f.bff.v1.ListAuditEventsResponse\"\x00\x12l\n" +
	"\x17CreateCommentAuditEvent\x12&.bff.v1.CreateCommentAuditEventRequest\x1a'.bff.v1.CreateCommentAuditEventResponse\"\x00\x12B\n" +
	"\tListRoles\x12\x18.bff.v1.ListRolesRequest\x1a\x19.bff.v1.ListRolesResponse\"\x00\x12H\n" +
	"\vAssignRoles\x12\x1a.bff.v1.AssignRolesRequest\x1a\x1b.bff.v1.AssignRolesResponse\"\x00\x12u\n" +
	"\x1aCreateAttachmentAuditEvent\x12).bff.v1.CreateAttachmentAuditEventRequest\x1a*.bff.v1.CreateAttachmentAuditEventResponse\"\x00\x12N\n" +
	"\rGetAttachment\x12\x1c.bff.v1.GetAttachmentRequest\x1a\x1d.bff.v1.GetAttachmentResponse\"\x00B<Z:github.com/strideynet/bsky-furry-feed/proto/bff/v1;bffv1pbb\x06proto3"

var (
	file_bff_v1_moderation_service_proto_rawDescOnce sync.Once
	file_bff_v1_moderation_service_proto_rawDescData []byte
)

func file_bff_v1_moderation_service_proto_rawDescGZIP() []byte {
	file_bff_v1_moderation_service_proto_rawDescOnce.Do(func() {
		file_bff_v1_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_v1_moderation_service_proto_rawDesc), len(file_bff_v1_moderation_service_proto_rawDesc)))
	})
	return file_bff_v1_moderation_service_proto_rawDescData
}

var file_bff_v1_moderation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bff_v1_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_bff_v1_moderation_service_proto_goTypes = []any{
	(ApprovalQueueAction)(0),                   // 0: bff.v1.ApprovalQueueAction
	(AuditEventType)(0),                        // 1: bff.v1.AuditEventType
	(*Post)(nil),                               // 2: bff.v1.Post
	(*GetActorRequest)(nil),                    // 3: bff.v1.GetActorRequest
	(*GetActorResponse)(nil),                   // 4: bff.v1.GetActorResponse
	(*ListActorsRequest)(nil),                  // 5: bff.v1.ListActorsRequest
	(*ListActorsResponse)(nil),                 // 6: bff.v1.ListActorsResponse
	(*PingRequest)(nil),                        // 7: bff.v1.PingRequest
	(*PingResponse)(nil),                       // 8: bff.v1.PingResponse
	(*ProcessApprovalQueueRequest)(nil),        // 9: bff.v1.ProcessApprovalQueueRequest
	(*ProcessApprovalQueueResponse)(nil),       // 10: bff.v1.ProcessApprovalQueueResponse
	(*ProcessApprovalQueueAuditPayload)(nil),   // 11: bff.v1.ProcessApprovalQueueAuditPayload
	(*HoldBackPendingActorRequest)(nil),        // 12: bff.v1.HoldBackPendingActorRequest
	(*HoldBackPendingActorResponse)(nil),       // 13: bff.v1.HoldBackPendingActorResponse
	(*HoldBackPendingActorAuditPayload)(nil),   // 14: bff.v1.HoldBackPendingActorAuditPayload
	(*ListAuditEventsRequest)(nil),             // 15: bff.v1.ListAuditEventsRequest
	(*ListAuditEventsResponse)(nil),            // 16: bff.v1.ListAuditEventsResponse
	(*CreateCommentAuditEventRequest)(nil),     // 17: bff.v1.CreateCommentAuditEventRequest
	(*CreateCommentAuditEventResponse)(nil),    // 18: bff.v1.CreateCommentAuditEventResponse
	(*CommentAuditPayload)(nil),                // 19: bff.v1.CommentAuditPayload
	(*CreateActorRequest)(nil),                 // 20: bff.v1.CreateActorRequest
	(*CreateActorResponse)(nil),                // 21: bff.v1.CreateActorResponse
	(*CreateActorAuditPayload)(nil),            // 22: bff.v1.CreateActorAuditPayload
	(*UnapproveActorRequest)(nil),              // 23: bff.v1.UnapproveActorRequest
	(*UnapproveActorResponse)(nil),             // 24: bff.v1.UnapproveActorResponse
	(*UnapproveActorAuditPayload)(nil),         // 25: bff.v1.UnapproveActorAuditPayload
	(*ForceApproveActorRequest)(nil),           // 26: bff.v1.ForceApproveActorRequest
	(*ForceApproveActorResponse)(nil),          // 27: bff.v1.ForceApproveActorResponse
	(*ForceApproveActorAuditPayload)(nil),      // 28: bff.v1.ForceApproveActorAuditPayload
	(*BanActorRequest)(nil),                    // 29: bff.v1.BanActorRequest
	(*BanActorResponse)(nil),                   // 30: bff.v1.BanActorResponse
	(*BanActorAuditPayload)(nil),               // 31: bff.v1.BanActorAuditPayload
	(*AuditEvent)(nil),                         // 32: bff.v1.AuditEvent
	(*ListRolesRequest)(nil),                   // 33: bff.v1.ListRolesRequest
	(*ListRolesResponse)(nil),                  // 34: bff.v1.ListRolesResponse
	(*Role)(nil),                               // 35: bff.v1.Role
	(*AssignRolesRequest)(nil),                 // 36: bff.v1.AssignRolesRequest
	(*AssignRolesResponse)(nil),                // 37: bff.v1.AssignRolesResponse
	(*AssignRolesAuditPayload)(nil),            // 38: bff.v1.AssignRolesAuditPayload
	(*AttachmentAuditEventPayload)(nil),        // 39: bff.v1.AttachmentAuditEventPayload
	(*CreateAttachmentAuditEventRequest)(nil),  // 40: bff.v1.CreateAttachmentAuditEventRequest
	(*CreateAttachmentAuditEventResponse)(nil), // 41: bff.v1.CreateAttachmentAuditEventResponse
	(*GetAttachmentRequest)(nil),               // 42: bff.v1.GetAttachmentRequest
	(*GetAttachmentResponse)(nil),              // 43: bff.v1.GetAttachmentResponse
	nil,                                        // 44: bff.v1.ListRolesResponse.RolesEntry
	(*timestamppb.Timestamp)(nil),              // 45: google.protobuf.Timestamp
	(*Actor)(nil),                              // 46: bff.v1.Actor
	(ActorStatus)(0),                           // 47: bff.v1.ActorStatus
	(*durationpb.Duration)(nil),                // 48: google.protobuf.Duration
	(*anypb.Any)(nil),                          // 49: google.protobuf.Any
}
var file_bff_v1_moderation_service_proto_depIdxs = []int32{
	45, // 0: bff.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	45, // 1: bff.v1.Post.indexed_at:type_name -> google.protobuf.Timestamp
	46, // 2: bff.v1.GetActorResponse.actor:type_name -> bff.v1.Actor
	47, // 3: bff.v1.ListActorsRequest.filter_status:type_name -> bff.v1.ActorStatus
	46, // 4: bff.v1.ListActorsResponse.actors:type_name -> bff.v1.Actor
	0,  // 5: bff.v1.ProcessApprovalQueueRequest.action:type_name -> bff.v1.ApprovalQueueAction
	0,  // 6: bff.v1.ProcessApprovalQueueAuditPayload.action:type_name -> bff.v1.ApprovalQueueAction
	48, // 7: bff.v1.HoldBackPendingActorRequest.duration:type_name -> google.protobuf.Duration
	45, // 8: bff.v1.HoldBackPendingActorAuditPayload.held_until:type_name -> google.protobuf.Timestamp
	1,  // 9: bff.v1.ListAuditEventsRequest.filter_types:type_name -> bff.v1.AuditEventType
	32, // 10: bff.v1.ListAuditEventsResponse.audit_events:type_name -> bff.v1.AuditEvent
	32, // 11: bff.v1.CreateCommentAuditEventResponse.audit_event:type_name -> bff.v1.AuditEvent
	46, // 12: bff.v1.CreateActorResponse.actor:type_name -> bff.v1.Actor
	46, // 13: bff.v1.UnapproveActorResponse.actor:type_name -> bff.v1.Actor
	46, // 14: bff.v1.ForceApproveActorResponse.actor:type_name -> bff.v1.Actor
	46, // 15: bff.v1.BanActorResponse.actor:type_name -> bff.v1.Actor
	45, // 16: bff.v1.AuditEvent.created_at:type_name -> google.protobuf.Timestamp
	49, // 17: bff.v1.AuditEvent.payload:type_name -> google.protobuf.Any
	44, // 18: bff.v1.ListRolesResponse.roles:type_name -> bff.v1.ListRolesResponse.RolesEntry
	35, // 19: bff.v1.ListRolesResponse.RolesEntry.value:type_name -> bff.v1.Role
	7,  // 20: bff.v1.ModerationService.Ping:input_type -> bff.v1.PingRequest
	9,  // 21: bff.v1.ModerationService.ProcessApprovalQueue:input_type -> bff.v1.ProcessApprovalQueueRequest
	12, // 22: bff.v1.ModerationService.HoldBackPendingActor:input_type -> bff.v1.HoldBackPendingActorRequest
	5,  // 23: bff.v1.ModerationService.ListActors:input_type -> bff.v1.ListActorsRequest
	3,  // 24: bff.v1.ModerationService.GetActor:input_type -> bff.v1.GetActorRequest
	29, // 25: bff.v1.ModerationService.BanActor:input_type -> bff.v1.BanActorRequest
	23, // 26: bff.v1.ModerationService.UnapproveActor:input_type -> bff.v1.UnapproveActorRequest
	26, // 27: bff.v1.ModerationService.ForceApproveActor:input_type -> bff.v1.ForceApproveActorRequest
	20, // 28: bff.v1.ModerationService.CreateActor:input_type -> bff.v1.CreateActorRequest
	15, // 29: bff.v1.ModerationService.ListAuditEvents:input_type -> bff.v1.ListAuditEventsRequest
	17, // 30: bff.v1.ModerationService.CreateCommentAuditEvent:input_type -> bff.v1.CreateCommentAuditEventRequest
	33, // 31: bff.v1.ModerationService.ListRoles:input_type -> bff.v1.ListRolesRequest
	36, // 32: bff.v1.ModerationService.AssignRoles:input_type -> bff.v1.AssignRolesRequest
	40, // 33: bff.v1.ModerationService.CreateAttachmentAuditEvent:input_type -> bff.v1.CreateAttachmentAuditEventRequest
	42, // 34: bff.v1.ModerationService.GetAttachment:input_type -> bff.v1.GetAttachmentRequest
	8,  // 35: bff.v1.ModerationService.Ping:output_type -> bff.v1.PingResponse
	10, // 36: bff.v1.ModerationService.ProcessApprovalQueue:output_type -> bff.v1.ProcessApprovalQueueResponse
	13, // 37: bff.v1.ModerationService.HoldBackPendingActor:output_type -> bff.v1.HoldBackPendingActorResponse
	6,  // 38: bff.v1.ModerationService.ListActors:output_type -> bff.v1.ListActorsResponse
	4,  // 39: bff.v1.ModerationService.GetActor:output_type -> bff.v1.GetActorResponse
	30, // 40: bff.v1.ModerationService.BanActor:output_type -> bff.v1.BanActorResponse
	24, // 41: bff.v1.ModerationService.UnapproveActor:output_type -> bff.v1.UnapproveActorResponse
	27, // 42: bff.v1.ModerationService.ForceApproveActor:output_type -> bff.v1.ForceApproveActorResponse
	21, // 43: bff.v1.ModerationService.CreateActor:output_type -> bff.v1.CreateActorResponse
	16, // 44: bff.v1.ModerationService.ListAuditEvents:output_type -> bff.v1.ListAuditEventsResponse
	18, // 45: bff.v1.ModerationService.CreateCommentAuditEvent:output_type -> bff.v1.CreateCommentAuditEventResponse
	34, // 46: bff.v1.ModerationService.ListRoles:output_type -> bff.v1.ListRolesResponse
	37, // 47: bff.v1.ModerationService.AssignRoles:output_type -> bff.v1.AssignRolesResponse
	41, // 48: bff.v1.ModerationService.CreateAttachmentAuditEvent:output_type -> bff.v1.CreateAttachmentAuditEventResponse
	43, // 49: bff.v1.ModerationService.GetAttachment:output_type -> bff.v1.GetAttachmentResponse
	35, // [35:50] is the sub-list for method output_type
	20, // [20:35] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_bff_v1_moderation_service_proto_init() }
func file_bff_v1_moderation_service_proto_init() {
	if File_bff_v1_moderation_service_proto != nil {
		return
	}
	file_bff_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_v1_moderation_service_proto_rawDesc), len(file_bff_v1_moderation_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_moderation_service_proto_goTypes,
		DependencyIndexes: file_bff_v1_moderation_service_proto_depIdxs,
		EnumInfos:         file_bff_v1_moderation_service_proto_enumTypes,
		MessageInfos:      file_bff_v1_moderation_service_proto_msgTypes,
	}.Build()
	File_bff_v1_moderation_service_proto = out.File
	file_bff_v1_moderation_service_proto_goTypes = nil
	file_bff_v1_moderation_service_proto_depIdxs = nil
}
