// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bff/v1/public_service.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsRequest) Reset() {
	*x = ListFeedsRequest{}
	mi := &file_bff_v1_public_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsRequest) ProtoMessage() {}

func (x *ListFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_public_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_public_service_proto_rawDescGZIP(), []int{0}
}

type ListFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feeds         []*Feed                `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedsResponse) Reset() {
	*x = ListFeedsResponse{}
	mi := &file_bff_v1_public_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedsResponse) ProtoMessage() {}

func (x *ListFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_public_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedsResponse.ProtoReflect.Descriptor instead.
func (*ListFeedsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_public_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type Feed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the feed. This is also the rkey it is
	// published under on bluesky.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// link is a link to the feed in the official Bluesky client.
	Link string `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	// display_name is the short name of the feed shown in the Bluesky client.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description is a long description of the feed shown in the Bluesky client.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// priority indicates where to show this feed in BFF UIs, allowing more
	// common feeds to be shown first. Higher priority wins. Negative values
	// indicate the feed should be hidden in the UI.
	Priority      int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_bff_v1_public_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_public_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_bff_v1_public_service_proto_rawDescGZIP(), []int{2}
}

func (x *Feed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feed) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Feed) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Feed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feed) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_bff_v1_public_service_proto protoreflect.FileDescriptor

const file_bff_v1_public_service_proto_rawDesc = "" +
	"\n" +
	"\x1bbff/v1/public_service.proto\x12\x06bff.v1\"\x12\n" +
	"\x10ListFeedsRequest\"7\n" +
	"\x11ListFeedsResponse\x12\"\n" +
	"\x05feeds\x18\x01 \x03(\v2\f.bff.v1.FeedR\x05feeds\"\x8b\x01\n" +
	"\x04Feed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority2S\n" +
	"\rPublicService\x12B\n" +
	"\tListFeeds\x12\x18.bff.v1.ListFeedsRequest\x1a\x19.bff.v1.ListFeedsResponse\"\x00B<Z:github.com/strideynet/bsky-furry-feed/proto/bff/v1;bffv1pbb\x06proto3"

var (
	file_bff_v1_public_service_proto_rawDescOnce sync.Once
	file_bff_v1_public_service_proto_rawDescData []byte
)

func file_bff_v1_public_service_proto_rawDescGZIP() []byte {
	file_bff_v1_public_service_proto_rawDescOnce.Do(func() {
		file_bff_v1_public_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_v1_public_service_proto_rawDesc), len(file_bff_v1_public_service_proto_rawDesc)))
	})
	return file_bff_v1_public_service_proto_rawDescData
}

var file_bff_v1_public_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bff_v1_public_service_proto_goTypes = []any{
	(*ListFeedsRequest)(nil),  // 0: bff.v1.ListFeedsRequest
	(*ListFeedsResponse)(nil), // 1: bff.v1.ListFeedsResponse
	(*Feed)(nil),              // 2: bff.v1.Feed
}
var file_bff_v1_public_service_proto_depIdxs = []int32{
	2, // 0: bff.v1.ListFeedsResponse.feeds:type_name -> bff.v1.Feed
	0, // 1: bff.v1.PublicService.ListFeeds:input_type -> bff.v1.ListFeedsRequest
	1, // 2: bff.v1.PublicService.ListFeeds:output_type -> bff.v1.ListFeedsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bff_v1_public_service_proto_init() }
func file_bff_v1_public_service_proto_init() {
	if File_bff_v1_public_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_v1_public_service_proto_rawDesc), len(file_bff_v1_public_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_public_service_proto_goTypes,
		DependencyIndexes: file_bff_v1_public_service_proto_depIdxs,
		MessageInfos:      file_bff_v1_public_service_proto_msgTypes,
	}.Build()
	File_bff_v1_public_service_proto = out.File
	file_bff_v1_public_service_proto_goTypes = nil
	file_bff_v1_public_service_proto_depIdxs = nil
}
