// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bff/v1/types.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorStatus int32

const (
	ActorStatus_ACTOR_STATUS_UNSPECIFIED ActorStatus = 0
	ActorStatus_ACTOR_STATUS_PENDING     ActorStatus = 1
	ActorStatus_ACTOR_STATUS_APPROVED    ActorStatus = 2
	ActorStatus_ACTOR_STATUS_BANNED      ActorStatus = 3
	ActorStatus_ACTOR_STATUS_NONE        ActorStatus = 4
)

// Enum value maps for ActorStatus.
var (
	ActorStatus_name = map[int32]string{
		0: "ACTOR_STATUS_UNSPECIFIED",
		1: "ACTOR_STATUS_PENDING",
		2: "ACTOR_STATUS_APPROVED",
		3: "ACTOR_STATUS_BANNED",
		4: "ACTOR_STATUS_NONE",
	}
	ActorStatus_value = map[string]int32{
		"ACTOR_STATUS_UNSPECIFIED": 0,
		"ACTOR_STATUS_PENDING":     1,
		"ACTOR_STATUS_APPROVED":    2,
		"ACTOR_STATUS_BANNED":      3,
		"ACTOR_STATUS_NONE":        4,
	}
)

func (x ActorStatus) Enum() *ActorStatus {
	p := new(ActorStatus)
	*p = x
	return p
}

func (x ActorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_v1_types_proto_enumTypes[0].Descriptor()
}

func (ActorStatus) Type() protoreflect.EnumType {
	return &file_bff_v1_types_proto_enumTypes[0]
}

func (x ActorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorStatus.Descriptor instead.
func (ActorStatus) EnumDescriptor() ([]byte, []int) {
	return file_bff_v1_types_proto_rawDescGZIP(), []int{0}
}

type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// did is the decentralized identity of the actor. This is also the UID used
	// for fetching and mutating actors.
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// is_artist is a flag indicating this account is primarily an artist. It
	// does not currently control any feed placement.
	IsArtist bool `protobuf:"varint,3,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	// comment is a short string that is applied to an account when it is added
	// to the system. This will eventually be replaced by a more powerful system.
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	// status indicates the actor's current status.
	Status ActorStatus `protobuf:"varint,5,opt,name=status,proto3,enum=bff.v1.ActorStatus" json:"status,omitempty"`
	// created_at indicates the time that the actor was first added to the bff
	// system - this does not necessarily indicate when they joined bluesky.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// roles is an array of roles this actor holds in relation to actions on the
	// moderation API.
	Roles []string `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	// held_until is the time until an actor with the PENDING status
	// is ignored in the queue to be processed later, e.g. when the actor doesn’t
	// have an avatar
	HeldUntil     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_bff_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_bff_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Actor) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *Actor) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Actor) GetStatus() ActorStatus {
	if x != nil {
		return x.Status
	}
	return ActorStatus_ACTOR_STATUS_UNSPECIFIED
}

func (x *Actor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Actor) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Actor) GetHeldUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

var File_bff_v1_types_proto protoreflect.FileDescriptor

const file_bff_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x12bff/v1/types.proto\x12\x06bff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x05Actor\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1b\n" +
	"\tis_artist\x18\x03 \x01(\bR\bisArtist\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.bff.v1.ActorStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05roles\x129\n" +
	"\n" +
	"held_until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\theldUntilJ\x04\b\x02\x10\x03*\x90\x01\n" +
	"\vActorStatus\x12\x1c\n" +
	"\x18ACTOR_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTOR_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ACTOR_STATUS_APPROVED\x10\x02\x12\x17\n" +
	"\x13ACTOR_STATUS_BANNED\x10\x03\x12\x15\n" +
	"\x11ACTOR_STATUS_NONE\x10\x04B<Z:github.com/strideynet/bsky-furry-feed/proto/bff/v1;bffv1pbb\x06proto3"

var (
	file_bff_v1_types_proto_rawDescOnce sync.Once
	file_bff_v1_types_proto_rawDescData []byte
)

func file_bff_v1_types_proto_rawDescGZIP() []byte {
	file_bff_v1_types_proto_rawDescOnce.Do(func() {
		file_bff_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_v1_types_proto_rawDesc), len(file_bff_v1_types_proto_rawDesc)))
	})
	return file_bff_v1_types_proto_rawDescData
}

var file_bff_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bff_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bff_v1_types_proto_goTypes = []any{
	(ActorStatus)(0),              // 0: bff.v1.ActorStatus
	(*Actor)(nil),                 // 1: bff.v1.Actor
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_bff_v1_types_proto_depIdxs = []int32{
	0, // 0: bff.v1.Actor.status:type_name -> bff.v1.ActorStatus
	2, // 1: bff.v1.Actor.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: bff.v1.Actor.held_until:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bff_v1_types_proto_init() }
func file_bff_v1_types_proto_init() {
	if File_bff_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_v1_types_proto_rawDesc), len(file_bff_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bff_v1_types_proto_goTypes,
		DependencyIndexes: file_bff_v1_types_proto_depIdxs,
		EnumInfos:         file_bff_v1_types_proto_enumTypes,
		MessageInfos:      file_bff_v1_types_proto_msgTypes,
	}.Build()
	File_bff_v1_types_proto = out.File
	file_bff_v1_types_proto_goTypes = nil
	file_bff_v1_types_proto_depIdxs = nil
}
