// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bff/v1/user_service.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_bff_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_user_service_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_bff_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type JoinApprovalQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinApprovalQueueRequest) Reset() {
	*x = JoinApprovalQueueRequest{}
	mi := &file_bff_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinApprovalQueueRequest) ProtoMessage() {}

func (x *JoinApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_user_service_proto_rawDescGZIP(), []int{2}
}

type JoinApprovalQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinApprovalQueueResponse) Reset() {
	*x = JoinApprovalQueueResponse{}
	mi := &file_bff_v1_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinApprovalQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinApprovalQueueResponse) ProtoMessage() {}

func (x *JoinApprovalQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinApprovalQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinApprovalQueueResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_user_service_proto_rawDescGZIP(), []int{3}
}

var File_bff_v1_user_service_proto protoreflect.FileDescriptor

const file_bff_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x19bff/v1/user_service.proto\x12\x06bff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x12bff/v1/types.proto\"\x0e\n" +
	"\fGetMeRequest\"4\n" +
	"\rGetMeResponse\x12#\n" +
	"\x05Actor\x18\x01 \x01(\v2\r.bff.v1.ActorR\x05Actor\"\x1a\n" +
	"\x18JoinApprovalQueueRequest\"\x1b\n" +
	"\x19JoinApprovalQueueResponse2\xa1\x01\n" +
	"\vUserService\x126\n" +
	"\x05GetMe\x12\x14.bff.v1.GetMeRequest\x1a\x15.bff.v1.GetMeResponse\"\x00\x12Z\n" +
	"\x11JoinApprovalQueue\x12 .bff.v1.JoinApprovalQueueRequest\x1a!.bff.v1.JoinApprovalQueueResponse\"\x00B<Z:github.com/strideynet/bsky-furry-feed/proto/bff/v1;bffv1pbb\x06proto3"

var (
	file_bff_v1_user_service_proto_rawDescOnce sync.Once
	file_bff_v1_user_service_proto_rawDescData []byte
)

func file_bff_v1_user_service_proto_rawDescGZIP() []byte {
	file_bff_v1_user_service_proto_rawDescOnce.Do(func() {
		file_bff_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_v1_user_service_proto_rawDesc), len(file_bff_v1_user_service_proto_rawDesc)))
	})
	return file_bff_v1_user_service_proto_rawDescData
}

var file_bff_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bff_v1_user_service_proto_goTypes = []any{
	(*GetMeRequest)(nil),              // 0: bff.v1.GetMeRequest
	(*GetMeResponse)(nil),             // 1: bff.v1.GetMeResponse
	(*JoinApprovalQueueRequest)(nil),  // 2: bff.v1.JoinApprovalQueueRequest
	(*JoinApprovalQueueResponse)(nil), // 3: bff.v1.JoinApprovalQueueResponse
	(*Actor)(nil),                     // 4: bff.v1.Actor
}
var file_bff_v1_user_service_proto_depIdxs = []int32{
	4, // 0: bff.v1.GetMeResponse.Actor:type_name -> bff.v1.Actor
	0, // 1: bff.v1.UserService.GetMe:input_type -> bff.v1.GetMeRequest
	2, // 2: bff.v1.UserService.JoinApprovalQueue:input_type -> bff.v1.JoinApprovalQueueRequest
	1, // 3: bff.v1.UserService.GetMe:output_type -> bff.v1.GetMeResponse
	3, // 4: bff.v1.UserService.JoinApprovalQueue:output_type -> bff.v1.JoinApprovalQueueResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bff_v1_user_service_proto_init() }
func file_bff_v1_user_service_proto_init() {
	if File_bff_v1_user_service_proto != nil {
		return
	}
	file_bff_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_v1_user_service_proto_rawDesc), len(file_bff_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_user_service_proto_goTypes,
		DependencyIndexes: file_bff_v1_user_service_proto_depIdxs,
		MessageInfos:      file_bff_v1_user_service_proto_msgTypes,
	}.Build()
	File_bff_v1_user_service_proto = out.File
	file_bff_v1_user_service_proto_goTypes = nil
	file_bff_v1_user_service_proto_depIdxs = nil
}
