name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go-unit:
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    name: "Go: Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Test
        run: go test -race -v ./...
